# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DypohuWnA1UdediWSczr6PDwPwk_-1Eh
"""

# Commented out IPython magic to ensure Python compatibility.
# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

# Clone repository
!git clone https://github.com/AliaksandrSiarohin/first-order-model
# %cd first-order-model

# Install dependencies
!pip install -r requirements.txt
!pip install imageio-ffmpeg

# Download pre-trained model
!gdown --id 1xB7nk2c3vL1aVe4nQ0tG3dt6a9rW9n8o -O vox-cpk.pth.tar

# Load and preprocess files
import imageio
import numpy as np
from skimage.transform import resize
source_image_path = '/content/gdrive/My Drive/first-order-motion-model/source_image.png'
driving_video_path = '/content/gdrive/My Drive/first-order-motion-model/driving_video.mp4'
source_image = resize(imageio.imread(source_image_path), (256, 256))[..., :3]
driving_video = [resize(frame, (256, 256))[..., :3] for frame in imageio.mimread(driving_video_path, memtest=False)]

# Load model and generate deepfake
from demo import load_checkpoints, make_animation
generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', checkpoint_path='vox-cpk.pth.tar')
predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=True, adapt_movement_scale=True)

# Save output
imageio.mimsave('/content/gdrive/My Drive/first-order-motion-model/output_video.mp4', [img for img in predictions], fps=30)